product: ucs
release: "5.0"
version: [0]
scope: ucs_5.0-0-errata5.0-0
src: univention-directory-replication
fix: 
desc: |
 This update addresses the following issue(s):
 * The applying of a failed.ldif has been repaired, it was broken due to the
   Python 3 migration.
bug: [53430]
