msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-appcenter\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-11-24 11:48+0100\n"
"PO-Revision-Date: 2020-09-15 14:46+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: German <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: __init__.py:88
msgid "Package not found in repository"
msgstr "Paket wurde in keinem Repository gefunden"

#: __init__.py:228
#, python-brace-format
msgid "Problems connecting to {0} ({1}). Please update {0}!"
msgstr ""

#: __init__.py:230
msgid "Problems connecting to {} ({})."
msgstr ""

#: __init__.py:231
msgid ""
"The App Center version of the this host ({}) is not compatible with the "
"version of {} ({})"
msgstr ""

#: __init__.py:306
#, python-format
msgid "%s: Running tests"
msgstr "%s: Starte Tests"

#: __init__.py:308
#, python-format
msgid "%d Apps: Running tests"
msgstr "%d Apps: Starte Tests"

#: __init__.py:330
#, python-format
msgid "Installing %s"
msgstr "Installiere %s"

#: __init__.py:332
#, python-format
msgid "Uninstalling %s"
msgstr "Deinstalliere %s"

#: __init__.py:334
#, python-format
msgid "Upgrading %s"
msgstr "Aktualisiere %s"

#: __init__.py:359
#, python-format
msgid "%s: Connecting to %s"
msgstr "%s: Verbinde zu %s"

#: __init__.py:361
#, python-format
msgid "%d Apps: Connecting to %s"
msgstr "%d Apps: Verbinde zu %s"

#: __init__.py:392
msgid ""
"The docker service is not running! The App Center will not work properly."
msgstr ""
"Der Docker-Dienst läuft nicht! Das App Center wird nicht richtig "
"funktionieren."

#: __init__.py:392 __init__.py:442
msgid ""
"Make sure docker.io is installed, try starting the service with \"service "
"docker start\"."
msgstr ""
"Stellen Sie sicher, dass docker.io installiert ist. Starten Sie den Dienst "
"mit \"service docker start\"."

#: __init__.py:411
msgid ""
"A conflict between the system network settings and the docker bridge default "
"network has been detected."
msgstr ""
"Es wurde ein Konflikt zwischen den Netzwerkeinstellungen des Systems und der "
"Docker Bridge entdeckt."

#: __init__.py:412
msgid ""
"Please either configure a different network for the docker bridge by setting "
"the UCR variable docker/daemon/default/opts/bip to a different network and "
"restart the system,"
msgstr ""
"Bitte konfigurieren Sie ein anderes Netzwerk für die Docker Bridge durch die "
"UCR Variable docker/daemon/default/opts/bip und ein Neustart des Systems,"

#: __init__.py:413
msgid ""
"or disable the docker support in the AppCenter by setting appcenter/docker "
"to false."
msgstr ""
"oder deaktivieren Sie die Unterstützung für Docker im AppCenter indem die "
"UCR Variable appcenter/docker auf false gesetzt wird."

#: __init__.py:430
msgid "Could not load suggestions."
msgstr "Konnte App-Vorschläge nicht laden."

#: __init__.py:435
msgid "Unexpected suggestions data."
msgstr "Unerwartete Daten für App-Vorschläge."

#: __init__.py:442
msgid "Unable to start the docker service!"
msgstr "Der Docker-Dienst konnte nicht gestartet werden!"

#: __init__.py:463 __init__.py:484 sanitizers.py:77
#, python-format
msgid "Could not find an application for %s"
msgstr "Konnte keine Applikation für %s finden"

#: __init__.py:545 __init__.py:867
msgid "Another package operation is in progress"
msgstr "Zur Zeit wird eine andere Paketverarbeitung durchgeführt"

#: __init__.py:564
#, python-format
msgid "Installing LDAP packages on %s"
msgstr "Installiere LDAP Pakete auf %s"

#: __init__.py:917
msgid "upgradable"
msgstr "aktualisierbar"

#: __init__.py:919
msgid "installed"
msgstr "installiert"

#: __init__.py:921
msgid "not installed"
msgstr "nicht installiert"

#: __init__.py:1020 __init__.py:1079
#, python-format
msgid "Invalid scheme, use http or https: %(base)r/%(key)r: %(value)r"
msgstr ""
"Ungültiges Schema, bitte http oder https benutzen:  %(base)r/%(key)r: "
"%(value)r"

#: sanitizers.py:54 sanitizers.py:58 sanitizers.py:62
msgid "Cannot connect to the LDAP service."
msgstr "Konnte nicht zum LDAP-Dienst verbinden."

#: sanitizers.py:54
msgid "The server seems to be lacking a proper password file."
msgstr "Dem Rechner scheint eine korrekte Passwortdatei zu fehlen."

#: sanitizers.py:54
msgid "Please check the join state of the machine."
msgstr "Bitte überprüfen Sie den Status des Domänenbeitritts."

#: sanitizers.py:58 sanitizers.py:62
msgid "The credentials provided were not accepted."
msgstr "Die Zugangsdaten wurden nicht akzeptiert."

#: sanitizers.py:58 sanitizers.py:62
msgid "This may be solved by simply logging out and in again."
msgstr ""
"Das Problem kann vielleicht bereits durch ein Aus- und erneutes Einloggen "
"gelöst werden."

#: sanitizers.py:58
msgid "Maybe your password changed during the session."
msgstr "Möglicherweise hat sich Ihr Passwort während der Sitzung geändert."

#: sanitizers.py:62
msgid "Maybe the machine password changed during the session."
msgstr ""
"Möglicherweise hat sich das Maschinenpasswort während der Sitzung geändert."

#: sanitizers.py:99
msgid "There already is a component with this name"
msgstr "Es gibt bereits eine Komponente mit diesem Namen"

#: util.py:197
#, python-format
msgid ""
"%s could not be downloaded. This seems to be a problem with the App Center "
"server. Please try again later."
msgstr ""
"Konnte %s nicht herunterladen. Das deutet auf ein Problem auf dem App Center-"
"Server hin. Bitte versuchen Sie es später noch einmal."

#: util.py:199
msgid "This is a problem with the App Center server. Please try again later."
msgstr ""
"Das ist ein Problem auf dem App Center-Server. Bitte versuchen Sie es später "
"noch einmal."

#: util.py:209
#, python-format
msgid ""
"https://docs.software-univention.de/manual-%s.html#ip-config:"
"Web_proxy_for_caching_and_policy_management__virus_scan"
msgstr ""
"https://docs.software-univention.de/handbuch-%s.html#ip-config:Web-"
"Proxy_fuer_Caching_und_Policy_Management_Virenscan"

#: util.py:210
#, python-format
msgid ""
"This may be a problem with the firewall or proxy of your system. You may "
"find help at %s."
msgstr ""
"Dies kann auf ein Problem mit einer auf Ihrem System eingerichteten Firewall "
"oder Proxy hindeuten. Sie finden Hilfe unter %s."

#: util.py:212
#, python-format
msgid "https://docs.software-univention.de/manual-%s.html#networks:dns"
msgstr "https://docs.software-univention.de/handbuch-%s.html#networks:dns"

#: util.py:213
#, python-format
msgid ""
"This is probably due to the DNS settings of your server. You may find help "
"at %s."
msgstr ""
"Grund sind wahrscheinlich die DNS-Einstellungen Ihres Servers. Sie finden "
"Hilfe unter %s."
